/* translate pins in naive.lisp to C
 *   written Thu 6-Oct-22 at 2:49 by CLM of 8-May-18
 */

#include <mus-config.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdarg.h>
#include <math.h>
#include <signal.h>
#include <cmus.h>

static sig_atomic_t got_sigint = 0; /* catch C-C if hung */
static void sig_err(int sig) {got_sigint = sig;}

int clm_pins2 (double *clm_double, int datar_len, int *clm_int, int datai_len)
{
  /* The _clm_* variables are temporary values generated by the run macro */
  void (*old_SIGINT)(int);
  mus_long_t I, TRIGGER, FILPTR, PEAKS, HOP, OUTHOP, MAX_PEAKS, HIGHEST_BIN, FFTSIZE, CUR_OSCILS, ATTACK_SIZE, _clm_5043, K, _clm_5051, _clm_5066, _clm_5078, _clm_5084, _clm_5101, MAX_OSCILS, _clm_5114, _clm_5126, J, _clm_5208, MAXP, _clm_5221, _clm_5250, _clm_5290, NEW_PLACE, _clm_5306, _clm_5346, _clm_5385, RAMP_IND, _clm_5425;
  bool _clm_5036, _clm_5044, _clm_5059, _clm_5067, _clm_5085, _clm_5102, _clm_5115, _clm_5127, _clm_5137, _clm_5140, _clm_5141, _clm_5143, _clm_5144, _clm_5146, _clm_5165, _clm_5177, _clm_5182, _clm_5192, _clm_5209, _clm_5222, _clm_5227, _clm_5237, _clm_5251, _clm_5255, _clm_5266, _clm_5274, _clm_5291, _clm_5295, _clm_5312, _clm_5317, _clm_5320, _clm_5321, _clm_5324, _clm_5347, _clm_5359, _clm_5362, _clm_5365, _clm_5386, _clm_5393, _clm_5396, _clm_5399, _clm_5410, _clm_5419, _clm_5426, _clm_5433, _clm_5436, _clm_5439;
  double SUM, FFT_MAG, IHIFREQ, IFREQ, LOWEST_MAGNITUDE, FURTHEST_AWAY_ACCEPTED, AMP, TRANSPOSITION, _clm_5025, RAMP, _clm_5027, _clm_5028, _clm_5030, MULT, _clm_5048, _clm_5050, _clm_5071, _clm_5072, _clm_5074, _clm_5088, X, _clm_5089, Y, _clm_5092, _clm_5093, _clm_5094, _clm_5095, _clm_5096, _clm_5105, _clm_5107, _clm_5120, RA, LA, CA, _clm_5132, _clm_5148, LOGLA, _clm_5149, LOGCA, _clm_5150, LOGRA, _clm_5151, _clm_5152, _clm_5153, _clm_5154, _clm_5155, OFFSET, _clm_5156, _clm_5157, _clm_5158, _clm_5159, _clm_5160, _clm_5161, FREQ, _clm_5167, MINPEAK, _clm_5183, _clm_5187, _clm_5212, MAXPK, _clm_5228, _clm_5232, _clm_5240, CURRENT_FREQ, _clm_5241, ICF, _clm_5256, _clm_5258, _clm_5259, _clm_5260, _clm_5261, CLOSENESS, _clm_5277, _clm_5296, _clm_5322, _clm_5325, _clm_5330, _clm_5334, _clm_5336, _clm_5338, _clm_5339, _clm_5351, _clm_5352, _clm_5353, _clm_5354, _clm_5363, _clm_5366, _clm_5370, _clm_5371, _clm_5372, _clm_5373, _clm_5397, _clm_5400, _clm_5403, _clm_5404, _clm_5405, _clm_5414, _clm_5437, _clm_5440, _clm_5443, _clm_5444, _clm_5445, _clm_5447, _clm_5449, _clm_5451, _clm_5453, _clm_5454;
  double *FFTAMPS = NULL, *FDR = NULL, *FDI = NULL, *WINDOW = NULL, *CURRENT_PEAK_FREQS = NULL, *LAST_PEAK_FREQS = NULL, *LAST_PEAK_AMPS = NULL, *PEAK_AMPS = NULL, *AMPS = NULL, *RATES = NULL, *FREQS = NULL, *SWEEPS = NULL, *PEAK_FREQS = NULL, *CURRENT_PEAK_AMPS = NULL, *RAMPED_ATTACK = NULL;
  mus_any *FIL = NULL, *_OUTPUT_ = NULL, *_clm_5340 = NULL, *_clm_5446 = NULL;
  mus_any **RESYNTH_OSCILS_array = NULL;
  void *all_gens = NULL;
  mus_long_t clm_beg, clm_end;
  double AMP_1; 
  all_gens = clm_make_genbag();
  clm_beg = clm_to_mus_long_t(clm_int, 1);
  clm_end = clm_to_mus_long_t(clm_int, 3);
  RAMP_IND = clm_int[35];
  #define RAMPED 7
  #define RAMPED_r 1
  #define PRINTIT 9
  #define PRINTIT_r 2
  #define _clm_5308 13
  #define _clm_5308_r 4
  #define HAPPY 15
  #define HAPPY_r 5
  NEW_PLACE = clm_int[37];
  #define CLOSESTAMP 17
  #define CLOSESTAMP_r 6
  #define CLOSESTP 19
  #define CLOSESTP_r 7
  MAXP = clm_int[39];
  #define _clm_5176 21
  #define _clm_5176_r 8
  J = clm_int[41];
  #define MINP 23
  #define MINP_r 9
  MAX_OSCILS = clm_int[43];
  _OUTPUT_ = clm_output();
  if ((CLM_FILE2SAMPLE_P(27)) || (CLM_FILE2FRAMPLE_P(27)))
    FIL = clm_add_gen_to_genbag(all_gens, 
      mus_make_file_to_sample_with_buffer_size((char *)(clm_int + CLM_ILOC(27) + 2 + 2), clm_int[CLM_ILOC(27) + 1]));
  #define SPLICE_ATTACK 29
  #define SPLICE_ATTACK_r 12
  if (CLM_VAR_TYPE(45) != CLM_NO_TYPE) RAMPED_ATTACK = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(45)));
  if (CLM_VAR_TYPE(47) != CLM_NO_TYPE) CURRENT_PEAK_AMPS = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(47)));
  if (CLM_VAR_TYPE(49) != CLM_NO_TYPE) PEAK_FREQS = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(49)));
  if (CLM_VAR_TYPE(51) != CLM_NO_TYPE) SWEEPS = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(51)));
  if (CLM_VAR_TYPE(53) != CLM_NO_TYPE) FREQS = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(53)));
  if (CLM_VAR_TYPE(55) != CLM_NO_TYPE) RATES = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(55)));
  if (CLM_VAR_TYPE(57) != CLM_NO_TYPE) AMPS = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(57)));
  if (CLM_VAR_TYPE(59) != CLM_NO_TYPE) PEAK_AMPS = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(59)));
  if (CLM_VAR_TYPE(61) != CLM_NO_TYPE) LAST_PEAK_AMPS = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(61)));
  if (CLM_VAR_TYPE(63) != CLM_NO_TYPE) LAST_PEAK_FREQS = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(63)));
  if (CLM_VAR_TYPE(65) != CLM_NO_TYPE) CURRENT_PEAK_FREQS = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(65)));
  if (CLM_VAR_TYPE(67) != CLM_NO_TYPE) WINDOW = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(67)));
  if (CLM_VAR_TYPE(69) != CLM_NO_TYPE) FDI = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(69)));
  if (CLM_VAR_TYPE(71) != CLM_NO_TYPE) FDR = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(71)));
  if (CLM_VAR_TYPE(73) != CLM_NO_TYPE) FFTAMPS = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(73)));
  #define RESYNTH_OSCILS 31
  #define RESYNTH_OSCILS_r 13
  if (CLM_ARRAY_P(RESYNTH_OSCILS))
    {
      RESYNTH_OSCILS_array = (mus_any **)calloc(CLM_ARR_SIZE(CLM_VAR_ADDR(RESYNTH_OSCILS)), sizeof(mus_any *));
      { /* load RESYNTH_OSCILS array */
       int i;
       for (i = 0; i < CLM_ARR_SIZE(CLM_VAR_ADDR(RESYNTH_OSCILS)); i++)
         if (clm_int[CLM_ARR_IBLOCK(CLM_VAR_ADDR(RESYNTH_OSCILS)) + (i * 2) + 1] != 0)
            {
              if (CLM_OSCIL_P(CLM_ARR_IBLOCK(CLM_VAR_ADDR(RESYNTH_OSCILS)) + (i * 2)))
                RESYNTH_OSCILS_array[i] = clm_add_gen_to_genbag(all_gens, 
                  mus_make_oscil(
                    mus_radians_to_hz(clm_double[CLM_RLOC(CLM_ARR_IBLOCK(CLM_VAR_ADDR(RESYNTH_OSCILS)) + (i * 2))]),
                    clm_double[CLM_RLOC(CLM_ARR_IBLOCK(CLM_VAR_ADDR(RESYNTH_OSCILS)) + (i * 2)) + 1]));
    }}}
  TRANSPOSITION = clm_double[15];
  AMP = clm_double[16];
  AMP_1 = clm_double[17];
  FURTHEST_AWAY_ACCEPTED = clm_double[18];
  LOWEST_MAGNITUDE = clm_double[19];
  IFREQ = clm_double[20];
  IHIFREQ = clm_double[21];
  FFT_MAG = clm_double[22];
  SUM = clm_double[23];
  ATTACK_SIZE = clm_int[75];
  CUR_OSCILS = clm_int[77];
  FFTSIZE = clm_int[79];
  HIGHEST_BIN = clm_int[81];
  MAX_PEAKS = clm_int[83];
  OUTHOP = clm_int[85];
  HOP = clm_int[87];
  PEAKS = clm_int[89];
  FILPTR = clm_int[91];
  TRIGGER = clm_int[93];
  I = clm_int[95];
  if (clm_beg > clm_end) return(1);
  got_sigint = 0; old_SIGINT = clm_signal(SIGINT, sig_err);                     /* trap SIGINT */
  I = clm_beg;                                                                  /* pass counter */

SAMPLE_LOOP_BEGIN:
  if (got_sigint != 0) {clm_int[0] = (int)got_sigint; goto RUN_ALL_DONE;}
  if (I > clm_end) {I = clm_end; goto RUN_ALL_DONE;}
                                                                                /* (progn */
                                                                                /* (if splice-attack */
  if (((clm_int[SPLICE_ATTACK] == 0) && (clm_int[SPLICE_ATTACK + 1] == 0))) goto L_5022;
  _clm_5025 = ((double)1.0 / (double)((ATTACK_SIZE)));
                                                                                /* (/ 1.0 attack-size) */
  RAMP = _clm_5025;                                                             /* (setf RAMP _clm_5025) */
  _clm_5030 = mus_in_any(FILPTR, 0, FIL);
                                                                                /* (* amp _clm_5030) */
  _clm_5028 = ((AMP) * (_clm_5030));
  _clm_5027 = mus_out_any(I, _clm_5028, 0, _OUTPUT_);
  FILPTR += 1;                                                                  /* (incf FILPTR 1) */
                                                                                /* (if (> filptr attack-size) */
  _clm_5036 = (FILPTR > ATTACK_SIZE);                                           /* (> FILPTR ATTACK-SIZE) */
  if ((!_clm_5036)) goto L_5034;
                                                                                /* (progn */
  MULT = 1.0;                                                                   /* (setf MULT 1.0) */
                                                                                /* (dotimes (k attack-size) */
  K = 0;                                                                        /* (setf K 0) */
  _clm_5043 = ATTACK_SIZE;                                                      /* (setf _clm_5043 ATTACK-SIZE) */
L_5040:
  _clm_5044 = (_clm_5043 > K);                                                  /* (> _clm_5043 K) */
  if (_clm_5044) goto L_5041;
  goto L_5042;
L_5041:
                                                                                /* (+ filptr k) */
  _clm_5051 = ((FILPTR) + (K));
  _clm_5050 = mus_in_any(_clm_5051, 0, FIL);
                                                                                /* (* mult _clm_5050) */
  _clm_5048 = ((MULT) * (_clm_5050));
  RAMPED_ATTACK[(int)(K)] = _clm_5048;
  MULT -= RAMP;                                                                 /* (decf MULT RAMP) */
  K += 1;                                                                       /* (incf K 1) */
  goto L_5040;
L_5042:
  
clm_int[SPLICE_ATTACK + 0] = 0;
  clm_int[SPLICE_ATTACK + 0 + 1] = 0;                                           /* (setf SPLICE-ATTACK NIL) */
  goto L_5035;
L_5034:
L_5035:
  goto L_5023;
L_5022:
                                                                                /* (progn */
                                                                                /* (if (>= trigger outhop) */
  _clm_5059 = (TRIGGER >= OUTHOP);                                              /* (>= TRIGGER OUTHOP) */
  if ((!_clm_5059)) goto L_5057;
                                                                                /* (progn */
  TRIGGER = 0;                                                                  /* (setf TRIGGER 0) */
                                                                                /* (dotimes (k fftsize) */
  K = 0;                                                                        /* (setf K 0) */
  _clm_5066 = FFTSIZE;                                                          /* (setf _clm_5066 FFTSIZE) */
L_5063:
  _clm_5067 = (_clm_5066 > K);                                                  /* (> _clm_5066 K) */
  if (_clm_5067) goto L_5064;
  goto L_5065;
L_5064:
  _clm_5072 = WINDOW[(int)(K)];
  _clm_5074 = mus_in_any(FILPTR, 0, FIL);
                                                                                /* (* _clm_5072 _clm_5074) */
  _clm_5071 = ((_clm_5072) * (_clm_5074));
  FDR[(int)(K)] = _clm_5071;
  FILPTR += 1;                                                                  /* (incf FILPTR 1) */
  K += 1;                                                                       /* (incf K 1) */
  goto L_5063;
L_5065:
  memset((void *)(FDI), 0, (CLM_ARR_SIZE(CLM_VAR_ADDR(69))) * sizeof(mus_float_t));
                                                                                /* (- fftsize hop) */
  _clm_5078 = ((FFTSIZE) - (HOP));
  FILPTR -= _clm_5078;                                                          /* (decf FILPTR _clm_5078) */
  mus_fft(FDR, FDI, FFTSIZE, 1);                                                /* (dotimes (k highest-bin) */
  K = 0;                                                                        /* (setf K 0) */
  _clm_5084 = HIGHEST_BIN;                                                      /* (setf _clm_5084 HIGHEST-BIN) */
L_5081:
  _clm_5085 = (_clm_5084 > K);                                                  /* (> _clm_5084 K) */
  if (_clm_5085) goto L_5082;
  goto L_5083;
L_5082:
  _clm_5088 = FDR[(int)(K)];
  X = _clm_5088;                                                                /* (setf X _clm_5088) */
  _clm_5089 = FDI[(int)(K)];
  Y = _clm_5089;                                                                /* (setf Y _clm_5089) */
                                                                                /* (* x x) */
  _clm_5095 = ((X) * (X));
                                                                                /* (* y y) */
  _clm_5096 = ((Y) * (Y));
                                                                                /* (+ _clm_5095 _clm_5096) */
  _clm_5094 = ((_clm_5095) + (_clm_5096));
  _clm_5093 = sqrt((double)(_clm_5094));                                        /* (sqrt _clm_5094) */
                                                                                /* (* 2 _clm_5093) */
  _clm_5092 = ((2) * (_clm_5093));
  FFTAMPS[(int)(K)] = _clm_5092;
  K += 1;                                                                       /* (incf K 1) */
  goto L_5081;
L_5083:
                                                                                /* (dotimes (k max-oscils) */
  K = 0;                                                                        /* (setf K 0) */
  _clm_5101 = MAX_OSCILS;                                                       /* (setf _clm_5101 MAX-OSCILS) */
L_5098:
  _clm_5102 = (_clm_5101 > K);                                                  /* (> _clm_5101 K) */
  if (_clm_5102) goto L_5099;
  goto L_5100;
L_5099:
  _clm_5105 = CURRENT_PEAK_FREQS[(int)(K)];
  LAST_PEAK_FREQS[(int)(K)] = _clm_5105;
  _clm_5107 = CURRENT_PEAK_AMPS[(int)(K)];
  LAST_PEAK_AMPS[(int)(K)] = _clm_5107;
  CURRENT_PEAK_AMPS[(int)(K)] = 0.0;
  K += 1;                                                                       /* (incf K 1) */
  goto L_5098;
L_5100:
                                                                                /* (dotimes (k max-peaks) */
  K = 0;                                                                        /* (setf K 0) */
  _clm_5114 = MAX_PEAKS;                                                        /* (setf _clm_5114 MAX-PEAKS) */
L_5111:
  _clm_5115 = (_clm_5114 > K);                                                  /* (> _clm_5114 K) */
  if (_clm_5115) goto L_5112;
  goto L_5113;
L_5112:
  PEAK_AMPS[(int)(K)] = 0.0;
  K += 1;                                                                       /* (incf K 1) */
  goto L_5111;
L_5113:
  _clm_5120 = FFTAMPS[(int)(0)];
  RA = _clm_5120;                                                               /* (setf RA _clm_5120) */
  LA = 0.0;                                                                     /* (setf LA 0.0) */
  CA = 0.0;                                                                     /* (setf CA 0.0) */
  PEAKS = 0;                                                                    /* (setf PEAKS 0) */
                                                                                /* (dotimes (k highest-bin) */
  K = 0;                                                                        /* (setf K 0) */
  _clm_5126 = HIGHEST_BIN;                                                      /* (setf _clm_5126 HIGHEST-BIN) */
L_5123:
  _clm_5127 = (_clm_5126 > K);                                                  /* (> _clm_5126 K) */
  if (_clm_5127) goto L_5124;
  goto L_5125;
L_5124:
  LA = CA;                                                                      /* (setf LA CA) */
  CA = RA;                                                                      /* (setf CA RA) */
  _clm_5132 = FFTAMPS[(int)(K)];
  RA = _clm_5132;                                                               /* (setf RA _clm_5132) */
                                                                                /* (if (and (> ca lowest-magnitude) (> ca ra) (> ca la)) */
                                                                                /* (cond */
  _clm_5141 = (CA > LOWEST_MAGNITUDE);                                          /* (> CA LOWEST-MAGNITUDE) */
  _clm_5140 = (!_clm_5141);                                                     /* (null _clm_5141) */
  _clm_5137 = _clm_5140;                                                        /* (setf _clm_5137 _clm_5140) */
  if ((!_clm_5140)) goto L_5139;
  _clm_5137 = 0;                                                                /* (setf _clm_5137 NIL) */
  goto L_5138;
L_5139:
  _clm_5144 = (CA > RA);                                                        /* (> CA RA) */
  _clm_5143 = (!_clm_5144);                                                     /* (null _clm_5144) */
  _clm_5137 = _clm_5143;                                                        /* (setf _clm_5137 _clm_5143) */
  if ((!_clm_5143)) goto L_5142;
  _clm_5137 = 0;                                                                /* (setf _clm_5137 NIL) */
  goto L_5138;
L_5142:
  _clm_5137 = 1;                                                                /* (setf _clm_5137 T) */
  _clm_5146 = (CA > LA);                                                        /* (> CA LA) */
  _clm_5137 = _clm_5146;                                                        /* (setf _clm_5137 _clm_5146) */
  goto L_5138;
L_5145:
  _clm_5137 = 0;                                                                /* (setf _clm_5137 NIL) */
L_5138:
  if ((!_clm_5137)) goto L_5134;
  _clm_5148 = log((double)(LA)) / 2.3025851;                                    /* (log LA 10) */
  LOGLA = _clm_5148;                                                            /* (setf LOGLA _clm_5148) */
  _clm_5149 = log((double)(CA)) / 2.3025851;                                    /* (log CA 10) */
  LOGCA = _clm_5149;                                                            /* (setf LOGCA _clm_5149) */
  _clm_5150 = log((double)(RA)) / 2.3025851;                                    /* (log RA 10) */
  LOGRA = _clm_5150;                                                            /* (setf LOGRA _clm_5150) */
                                                                                /* (- logla logra) */
  _clm_5153 = ((LOGLA) - (LOGRA));
                                                                                /* (* 0.5 _clm_5153) */
  _clm_5152 = ((0.5) * (_clm_5153));
                                                                                /* (* -2 logca) */
  _clm_5155 = ((-2) * (LOGCA));
                                                                                /* (+ logla _clm_5155 logra) */
  _clm_5154 = ((LOGLA) + (_clm_5155) + (LOGRA));
  _clm_5151 = ((double)_clm_5152 / (double)((_clm_5154)));
                                                                                /* (/ _clm_5152 _clm_5154) */
  OFFSET = _clm_5151;                                                           /* (setf OFFSET _clm_5151) */
                                                                                /* (- logla logra) */
  _clm_5159 = ((LOGLA) - (LOGRA));
                                                                                /* (* 0.25 _clm_5159 offset) */
  _clm_5158 = ((0.25) * (_clm_5159) * (OFFSET));
                                                                                /* (- logca _clm_5158) */
  _clm_5157 = ((LOGCA) - (_clm_5158));
  _clm_5156 = pow((double)(10.0), (double)(_clm_5157));                         /* (expt 10.0 _clm_5157) */
  AMP_1 = _clm_5156;                                                            /* (setf AMP _clm_5156) */
                                                                                /* (+ k offset -1) */
  _clm_5161 = ((K) + (OFFSET) + (-1));
                                                                                /* (* fft-mag _clm_5161) */
  _clm_5160 = ((FFT_MAG) * (_clm_5161));
  FREQ = _clm_5160;                                                             /* (setf FREQ _clm_5160) */
                                                                                /* (if (= peaks max-peaks) */
  _clm_5165 = (PEAKS == MAX_PEAKS);                                             /* (== PEAKS MAX-PEAKS) */
  if ((!_clm_5165)) goto L_5163;
  
clm_int[MINP + 0] = 1;
  clm_int[MINP + 0 + 1] = 0;                                                    /* (setf MINP 0) */
  _clm_5167 = PEAK_AMPS[(int)(0)];
  MINPEAK = _clm_5167;                                                          /* (setf MINPEAK _clm_5167) */
                                                                                /* (do */
  J = 1;                                                                        /* (setf J 1) */
  goto L_5174;
L_5171:
  
clm_int[_clm_5176 + 0] = 1;
  clm_int[_clm_5176 + 0 + 1] = J + 1;
  J = ((clm_int[_clm_5176] == 2) ? clm_double[_clm_5176_r] : (double)(clm_int[_clm_5176 + 1])); /* (setf J _clm_5176) */
L_5174:
L_5170:
  _clm_5177 = (J == MAX_PEAKS);                                                 /* (== J MAX-PEAKS) */
  if ((!_clm_5177)) goto L_5169;
  goto L_5172;
L_5169:
                                                                                /* (if (< (aref peak-amps j) minpeak) */
  _clm_5183 = PEAK_AMPS[(int)(J)];
  _clm_5182 = (_clm_5183 < MINPEAK);                                            /* (< _clm_5183 MINPEAK) */
  if ((!_clm_5182)) goto L_5180;
                                                                                /* (progn */
  
clm_int[MINP + 0] = 1;
  clm_int[MINP + 0 + 1] = J;                                                    /* (setf MINP J) */
  _clm_5187 = PEAK_AMPS[(int)(J)];
  MINPEAK = _clm_5187;                                                          /* (setf MINPEAK _clm_5187) */
  goto L_5181;
L_5180:
L_5181:
  goto L_5171;
L_5172:
                                                                                /* (if (> amp minpeak) */
  _clm_5192 = (AMP_1 > MINPEAK);                                                /* (> AMP MINPEAK) */
  if ((!_clm_5192)) goto L_5190;
                                                                                /* (progn */
  PEAK_FREQS[(int)(clm_int[MINP + 0 + 1])] = FREQ;
  PEAK_AMPS[(int)(clm_int[MINP + 0 + 1])] = AMP_1;
  goto L_5191;
L_5190:
L_5191:
  goto L_5164;
L_5163:
                                                                                /* (progn */
  PEAK_FREQS[(int)(PEAKS)] = FREQ;
  PEAK_AMPS[(int)(PEAKS)] = AMP_1;
  PEAKS += 1;                                                                   /* (incf PEAKS 1) */
L_5164:
  goto L_5135;
L_5134:
L_5135:
  K += 1;                                                                       /* (incf K 1) */
  goto L_5123;
L_5125:
                                                                                /* (dotimes (k peaks) */
  K = 0;                                                                        /* (setf K 0) */
  _clm_5208 = PEAKS;                                                            /* (setf _clm_5208 PEAKS) */
L_5205:
  _clm_5209 = (_clm_5208 > K);                                                  /* (> _clm_5208 K) */
  if (_clm_5209) goto L_5206;
  goto L_5207;
L_5206:
  MAXP = 0;                                                                     /* (setf MAXP 0) */
  _clm_5212 = PEAK_AMPS[(int)(0)];
  MAXPK = _clm_5212;                                                            /* (setf MAXPK _clm_5212) */
                                                                                /* (do */
  J = 1;                                                                        /* (setf J 1) */
  goto L_5219;
L_5216:
  _clm_5221 = J + 1;
  J = _clm_5221;                                                                /* (setf J _clm_5221) */
L_5219:
L_5215:
  _clm_5222 = (J == MAX_PEAKS);                                                 /* (== J MAX-PEAKS) */
  if ((!_clm_5222)) goto L_5214;
  goto L_5217;
L_5214:
                                                                                /* (if (> (aref peak-amps j) maxpk) */
  _clm_5228 = PEAK_AMPS[(int)(J)];
  _clm_5227 = (_clm_5228 > MAXPK);                                              /* (> _clm_5228 MAXPK) */
  if ((!_clm_5227)) goto L_5225;
                                                                                /* (progn */
  MAXP = J;                                                                     /* (setf MAXP J) */
  _clm_5232 = PEAK_AMPS[(int)(J)];
  MAXPK = _clm_5232;                                                            /* (setf MAXPK _clm_5232) */
  goto L_5226;
L_5225:
L_5226:
  goto L_5216;
L_5217:
                                                                                /* (if (> maxpk 0.0) */
  _clm_5237 = (MAXPK > 0.0);                                                    /* (> MAXPK 0.0) */
  if ((!_clm_5237)) goto L_5235;
                                                                                /* (progn */
  
clm_int[CLOSESTP + 0] = 1;
  clm_int[CLOSESTP + 0 + 1] = -1;                                               /* (setf CLOSESTP -1) */
  
clm_int[CLOSESTAMP + 0] = 1;
  clm_int[CLOSESTAMP + 0 + 1] = 10;                                             /* (setf CLOSESTAMP 10) */
  _clm_5240 = PEAK_FREQS[(int)(MAXP)];
  CURRENT_FREQ = _clm_5240;                                                     /* (setf CURRENT-FREQ _clm_5240) */
  _clm_5241 = ((double)1.0 / (double)((CURRENT_FREQ)));
                                                                                /* (/ 1.0 current-freq) */
  ICF = _clm_5241;                                                              /* (setf ICF _clm_5241) */
                                                                                /* (do */
  J = 0;                                                                        /* (setf J 0) */
  goto L_5248;
L_5245:
  _clm_5250 = J + 1;
  J = _clm_5250;                                                                /* (setf J _clm_5250) */
L_5248:
L_5244:
  _clm_5251 = (J == MAX_PEAKS);                                                 /* (== J MAX-PEAKS) */
  if ((!_clm_5251)) goto L_5243;
  goto L_5246;
L_5243:
                                                                                /* (if (> (aref last-peak-amps j) 0.0) */
  _clm_5256 = LAST_PEAK_AMPS[(int)(J)];
  _clm_5255 = (_clm_5256 > 0.0);                                                /* (> _clm_5256 0.0) */
  if ((!_clm_5255)) goto L_5253;
  _clm_5261 = LAST_PEAK_FREQS[(int)(J)];
                                                                                /* (- _clm_5261 current-freq) */
  _clm_5260 = ((_clm_5261) - (CURRENT_FREQ));
                                                                                /* (abs _clm_5260) */
  _clm_5259 = fabs(_clm_5260);
                                                                                /* (* icf _clm_5259) */
  _clm_5258 = ((ICF) * (_clm_5259));
  CLOSENESS = _clm_5258;                                                        /* (setf CLOSENESS _clm_5258) */
                                                                                /* (if (< closeness closestamp) */
  _clm_5266 = (CLOSENESS < ((clm_int[CLOSESTAMP] == 2) ? clm_double[CLOSESTAMP_r] : (double)(clm_int[CLOSESTAMP + 1]))); /* (< CLOSENESS CLOSESTAMP) */
  if ((!_clm_5266)) goto L_5264;
                                                                                /* (progn */
  
clm_int[CLOSESTAMP + 0] = 2;
  clm_double[CLOSESTAMP_r+0] = CLOSENESS;                                       /* (setf CLOSESTAMP CLOSENESS) */
  
clm_int[CLOSESTP + 0] = 1;
  clm_int[CLOSESTP + 0 + 1] = J;                                                /* (setf CLOSESTP J) */
  goto L_5265;
L_5264:
L_5265:
  goto L_5254;
L_5253:
L_5254:
  goto L_5245;
L_5246:
                                                                                /* (if (< closestamp furthest-away-accepted) */
  _clm_5274 = (((clm_int[CLOSESTAMP] == 2) ? clm_double[CLOSESTAMP_r] : (double)(clm_int[CLOSESTAMP + 1])) < FURTHEST_AWAY_ACCEPTED); /* (< CLOSESTAMP FURTHEST-AWAY-ACCEPTED) */
  if ((!_clm_5274)) goto L_5272;
                                                                                /* (progn */
  _clm_5277 = PEAK_AMPS[(int)(MAXP)];
  CURRENT_PEAK_AMPS[(int)(clm_int[CLOSESTP + 0 + 1])] = _clm_5277;
  PEAK_AMPS[(int)(MAXP)] = 0.0;
  CURRENT_PEAK_FREQS[(int)(clm_int[CLOSESTP + 0 + 1])] = CURRENT_FREQ;
  goto L_5273;
L_5272:
L_5273:
  goto L_5236;
L_5235:
L_5236:
  K += 1;                                                                       /* (incf K 1) */
  goto L_5205;
L_5207:
                                                                                /* (do */
  K = 0;                                                                        /* (setf K 0) */
  goto L_5288;
L_5285:
  _clm_5290 = K + 1;
  K = _clm_5290;                                                                /* (setf K _clm_5290) */
L_5288:
L_5284:
  _clm_5291 = (K == MAX_PEAKS);                                                 /* (== K MAX-PEAKS) */
  if ((!_clm_5291)) goto L_5283;
  goto L_5286;
L_5283:
                                                                                /* (if (> (aref peak-amps k) 0.0) */
  _clm_5296 = PEAK_AMPS[(int)(K)];
  _clm_5295 = (_clm_5296 > 0.0);                                                /* (> _clm_5296 0.0) */
  if ((!_clm_5295)) goto L_5293;
  NEW_PLACE = 0;                                                                /* (setf NEW-PLACE 0) */
  
clm_int[HAPPY + 0] = 0;
  clm_int[HAPPY + 0 + 1] = 0;                                                   /* (setf HAPPY NIL) */
                                                                                /* (do */
  J = 0;                                                                        /* (setf J 0) */
  goto L_5304;
L_5301:
  _clm_5306 = J + 1;
  J = _clm_5306;                                                                /* (setf J _clm_5306) */
L_5304:
L_5300:
                                                                                /* (cond */
  
clm_int[_clm_5308 + 0] = clm_int[HAPPY + 0];
  clm_int[_clm_5308 + 0 + 1] = clm_int[HAPPY + 0 + 1];
  clm_double[_clm_5308_r + 0] = clm_double[HAPPY_r + 0];                        /* (setf _clm_5308 HAPPY) */
  if (((clm_int[HAPPY] == 0) && (clm_int[HAPPY + 1] == 0))) goto L_5310;
  goto L_5309;
L_5310:
  
clm_int[_clm_5308 + 0] = 0;
  clm_int[_clm_5308 + 0 + 1] = 1;                                               /* (setf _clm_5308 T) */
  _clm_5312 = (J == MAX_OSCILS);                                                /* (== J MAX-OSCILS) */
  
clm_int[_clm_5308 + 0] = 0;
  clm_int[_clm_5308 + 0 + 1] = _clm_5312;                                       /* (setf _clm_5308 _clm_5312) */
  goto L_5309;
L_5311:
  
clm_int[_clm_5308 + 0] = 0;
  clm_int[_clm_5308 + 0 + 1] = 0;                                               /* (setf _clm_5308 NIL) */
L_5309:
  if (((clm_int[_clm_5308] == 0) && (clm_int[_clm_5308 + 1] == 0))) goto L_5299;
  goto L_5302;
L_5299:
                                                                                /* (if (and (zerop (aref last-peak-amps j)) (zerop (aref current-peak-amps j))) */
                                                                                /* (cond */
  _clm_5322 = LAST_PEAK_AMPS[(int)(J)];
  _clm_5321 = (_clm_5322 == 0.0);                                               /* (zerop _clm_5322) */
  _clm_5320 = (!_clm_5321);                                                     /* (null _clm_5321) */
  _clm_5317 = _clm_5320;                                                        /* (setf _clm_5317 _clm_5320) */
  if ((!_clm_5320)) goto L_5319;
  _clm_5317 = 0;                                                                /* (setf _clm_5317 NIL) */
  goto L_5318;
L_5319:
  _clm_5317 = 1;                                                                /* (setf _clm_5317 T) */
  _clm_5325 = CURRENT_PEAK_AMPS[(int)(J)];
  _clm_5324 = (_clm_5325 == 0.0);                                               /* (zerop _clm_5325) */
  _clm_5317 = _clm_5324;                                                        /* (setf _clm_5317 _clm_5324) */
  goto L_5318;
L_5323:
  _clm_5317 = 0;                                                                /* (setf _clm_5317 NIL) */
L_5318:
  if ((!_clm_5317)) goto L_5314;
                                                                                /* (progn */
  NEW_PLACE = J;                                                                /* (setf NEW-PLACE J) */
  
clm_int[HAPPY + 0] = 0;
  clm_int[HAPPY + 0 + 1] = 1;                                                   /* (setf HAPPY T) */
  goto L_5315;
L_5314:
L_5315:
  goto L_5301;
L_5302:
  _clm_5330 = PEAK_AMPS[(int)(K)];
  CURRENT_PEAK_AMPS[(int)(NEW_PLACE)] = _clm_5330;
  PEAK_AMPS[(int)(K)] = 0.0;
  _clm_5334 = PEAK_FREQS[(int)(K)];
  CURRENT_PEAK_FREQS[(int)(NEW_PLACE)] = _clm_5334;
  _clm_5336 = PEAK_FREQS[(int)(K)];
  LAST_PEAK_FREQS[(int)(NEW_PLACE)] = _clm_5336;
  _clm_5339 = PEAK_FREQS[(int)(K)];
                                                                                /* (* transposition _clm_5339) */
  _clm_5338 = ((TRANSPOSITION) * (_clm_5339));
  _clm_5340 = RESYNTH_OSCILS_array[(int)(NEW_PLACE)];
  mus_set_frequency(_clm_5340, _clm_5338);
  goto L_5294;
L_5293:
L_5294:
  goto L_5285;
L_5286:
  CUR_OSCILS = 0;                                                               /* (setf CUR-OSCILS 0) */
                                                                                /* (dotimes (k max-oscils) */
  K = 0;                                                                        /* (setf K 0) */
  _clm_5346 = MAX_OSCILS;                                                       /* (setf _clm_5346 MAX-OSCILS) */
L_5343:
  _clm_5347 = (_clm_5346 > K);                                                  /* (> _clm_5346 K) */
  if (_clm_5347) goto L_5344;
  goto L_5345;
L_5344:
  _clm_5353 = CURRENT_PEAK_AMPS[(int)(K)];
  _clm_5354 = LAST_PEAK_AMPS[(int)(K)];
                                                                                /* (- _clm_5353 _clm_5354) */
  _clm_5352 = ((_clm_5353) - (_clm_5354));
                                                                                /* (* ifreq _clm_5352) */
  _clm_5351 = ((IFREQ) * (_clm_5352));
  RATES[(int)(K)] = _clm_5351;
                                                                                /* (if (or (/= (aref current-peak-amps k) 0.0) (/= (aref last-peak-amps k) 0.0)) */
                                                                                /* (cond */
  _clm_5363 = CURRENT_PEAK_AMPS[(int)(K)];
  _clm_5362 = (_clm_5363 != 0.0);                                               /* (neq _clm_5363 0.0) */
  _clm_5359 = _clm_5362;                                                        /* (setf _clm_5359 _clm_5362) */
  if ((!_clm_5362)) goto L_5361;
  goto L_5360;
L_5361:
  _clm_5359 = 1;                                                                /* (setf _clm_5359 T) */
  _clm_5366 = LAST_PEAK_AMPS[(int)(K)];
  _clm_5365 = (_clm_5366 != 0.0);                                               /* (neq _clm_5366 0.0) */
  _clm_5359 = _clm_5365;                                                        /* (setf _clm_5359 _clm_5365) */
  goto L_5360;
L_5364:
  _clm_5359 = 0;                                                                /* (setf _clm_5359 NIL) */
L_5360:
  if ((!_clm_5359)) goto L_5356;
  CUR_OSCILS = K;                                                               /* (setf CUR-OSCILS K) */
  goto L_5357;
L_5356:
L_5357:
  _clm_5372 = CURRENT_PEAK_FREQS[(int)(K)];
  _clm_5373 = LAST_PEAK_FREQS[(int)(K)];
                                                                                /* (- _clm_5372 _clm_5373) */
  _clm_5371 = ((_clm_5372) - (_clm_5373));
                                                                                /* (* ihifreq transposition _clm_5371) */
  _clm_5370 = ((IHIFREQ) * (TRANSPOSITION) * (_clm_5371));
  SWEEPS[(int)(K)] = _clm_5370;
  K += 1;                                                                       /* (incf K 1) */
  goto L_5343;
L_5345:
  CUR_OSCILS += 1;                                                              /* (incf CUR-OSCILS 1) */
                                                                                /* (if printit */
  if (((clm_int[PRINTIT] == 0) && (clm_int[PRINTIT + 1] == 0))) goto L_5377;
                                                                                /* (progn */
                                                                                /* (clm-print "~%~%~D:"  FILPTR) */
  mus_error(0, 
"\n\n%" PRId64" :",
        (mus_long_t)FILPTR);
                                                                                /* (dotimes (k cur-oscils) */
  K = 0;                                                                        /* (setf K 0) */
  _clm_5385 = CUR_OSCILS;                                                       /* (setf _clm_5385 CUR-OSCILS) */
L_5382:
  _clm_5386 = (_clm_5385 > K);                                                  /* (> _clm_5385 K) */
  if (_clm_5386) goto L_5383;
  goto L_5384;
L_5383:
                                                                                /* (if (or (> (aref rates k) 0.0) (> (aref amps k) 0.0)) */
                                                                                /* (cond */
  _clm_5397 = RATES[(int)(K)];
  _clm_5396 = (_clm_5397 > 0.0);                                                /* (> _clm_5397 0.0) */
  _clm_5393 = _clm_5396;                                                        /* (setf _clm_5393 _clm_5396) */
  if ((!_clm_5396)) goto L_5395;
  goto L_5394;
L_5395:
  _clm_5393 = 1;                                                                /* (setf _clm_5393 T) */
  _clm_5400 = AMPS[(int)(K)];
  _clm_5399 = (_clm_5400 > 0.0);                                                /* (> _clm_5400 0.0) */
  _clm_5393 = _clm_5399;                                                        /* (setf _clm_5393 _clm_5399) */
  goto L_5394;
L_5398:
  _clm_5393 = 0;                                                                /* (setf _clm_5393 NIL) */
L_5394:
  if ((!_clm_5393)) goto L_5390;
                                                                                /* (progn */
  _clm_5403 = CURRENT_PEAK_FREQS[(int)(K)];
  _clm_5404 = LAST_PEAK_FREQS[(int)(K)];
  _clm_5405 = CURRENT_PEAK_AMPS[(int)(K)];
                                                                                /* (clm-print "~%  ~D ~F ~F ~F"  K _clm_5403 _clm_5404 _clm_5405) */
  mus_error(0, 
"\n  %" PRId64"  %f %f %f",
        (mus_long_t)K,
        (double)_clm_5403,
        (double)_clm_5404,
        (double)_clm_5405);
  goto L_5391;
L_5390:
L_5391:
  K += 1;                                                                       /* (incf K 1) */
  goto L_5382;
L_5384:
  goto L_5378;
L_5377:
L_5378:
  goto L_5058;
L_5057:
L_5058:
  TRIGGER += 1;                                                                 /* (incf TRIGGER 1) */
                                                                                /* (if (not ramped) */
  _clm_5410 = ((clm_int[RAMPED] == 0) && (clm_int[RAMPED + 1] == 0));           /* (null RAMPED) */
  if ((!_clm_5410)) goto L_5408;
  SUM = 0.0;                                                                    /* (setf SUM 0.0) */
  goto L_5409;
L_5408:
                                                                                /* (progn */
  _clm_5414 = RAMPED_ATTACK[(int)(RAMP_IND)];
  SUM = _clm_5414;                                                              /* (setf SUM _clm_5414) */
  RAMP_IND += 1;                                                                /* (incf RAMP-IND 1) */
                                                                                /* (if (= ramp-ind ramped) */
  _clm_5419 = (RAMP_IND == ((clm_int[RAMPED] == 2) ? clm_double[RAMPED_r] : (double)(clm_int[RAMPED + 1]))); /* (== RAMP-IND RAMPED) */
  if ((!_clm_5419)) goto L_5417;
  
clm_int[RAMPED + 0] = 0;
  clm_int[RAMPED + 0 + 1] = 0;                                                  /* (setf RAMPED NIL) */
  goto L_5418;
L_5417:
L_5418:
L_5409:
                                                                                /* (dotimes (k cur-oscils) */
  K = 0;                                                                        /* (setf K 0) */
  _clm_5425 = CUR_OSCILS;                                                       /* (setf _clm_5425 CUR-OSCILS) */
L_5422:
  _clm_5426 = (_clm_5425 > K);                                                  /* (> _clm_5425 K) */
  if (_clm_5426) goto L_5423;
  goto L_5424;
L_5423:
                                                                                /* (if (or (/= (aref amps k) 0.0) (/= (aref rates k) 0.0)) */
                                                                                /* (cond */
  _clm_5437 = AMPS[(int)(K)];
  _clm_5436 = (_clm_5437 != 0.0);                                               /* (neq _clm_5437 0.0) */
  _clm_5433 = _clm_5436;                                                        /* (setf _clm_5433 _clm_5436) */
  if ((!_clm_5436)) goto L_5435;
  goto L_5434;
L_5435:
  _clm_5433 = 1;                                                                /* (setf _clm_5433 T) */
  _clm_5440 = RATES[(int)(K)];
  _clm_5439 = (_clm_5440 != 0.0);                                               /* (neq _clm_5440 0.0) */
  _clm_5433 = _clm_5439;                                                        /* (setf _clm_5433 _clm_5439) */
  goto L_5434;
L_5438:
  _clm_5433 = 0;                                                                /* (setf _clm_5433 NIL) */
L_5434:
  if ((!_clm_5433)) goto L_5430;
                                                                                /* (progn */
  _clm_5444 = AMPS[(int)(K)];
  _clm_5446 = RESYNTH_OSCILS_array[(int)(K)];
  _clm_5447 = FREQS[(int)(K)];
  _clm_5445 = mus_oscil_fm(_clm_5446, _clm_5447);                               /* (oscil _clm_5446 _clm_5447) */
                                                                                /* (* _clm_5444 _clm_5445) */
  _clm_5443 = ((_clm_5444) * (_clm_5445));
  SUM += _clm_5443;                                                             /* (incf SUM _clm_5443) */
  _clm_5449 = RATES[(int)(K)];
  AMPS[(int)(K)] += _clm_5449;
  _clm_5451 = SWEEPS[(int)(K)];
  FREQS[(int)(K)] += _clm_5451;
  goto L_5431;
L_5430:
L_5431:
  K += 1;                                                                       /* (incf K 1) */
  goto L_5422;
L_5424:
                                                                                /* (* amp sum) */
  _clm_5454 = ((AMP) * (SUM));
  _clm_5453 = mus_out_any(I, _clm_5454, 0, _OUTPUT_);
L_5023:
  I++;                                                                          /* increment pass counter and loop */
goto SAMPLE_LOOP_BEGIN;

RUN_ALL_DONE:
  clm_signal(SIGINT,old_SIGINT);
  if (all_gens) clm_free_genbag(all_gens);
  if (RESYNTH_OSCILS_array) free(RESYNTH_OSCILS_array);

  return(1);
}

