/* translate fm-violin in naive.lisp to C
 *   written Mon 12-Sep-22 at 21:57 by CLM of 8-May-18
 */

#include <mus-config.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdarg.h>
#include <math.h>
#include <signal.h>
#include <cmus.h>

static sig_atomic_t got_sigint = 0; /* catch C-C if hung */
static void sig_err(int sig) {got_sigint = sig;}

int clm_fm_violin2 (double *clm_double, int datar_len, int *clm_int, int datai_len)
{
  /* The _clm_* variables are temporary values generated by the run macro */
  void (*old_SIGINT)(int);
  mus_long_t I;
  bool FROBBER, EASY_CASE, MODULATE, _clm_5060, _clm_5064;
  double NOISE_AMOUNT, FUZZ, IND_FUZZ, AMP_FUZZ, MODULATION, FM1_RAT, FM2_RAT, FM3_RAT, VIB, _clm_5066, _clm_5068, _clm_5070, _clm_5071, _clm_5072, _clm_5073, _clm_5078, _clm_5079, _clm_5084, _clm_5085, _clm_5093, _clm_5094, _clm_5095, _clm_5096, _clm_5098, _clm_5099, _clm_5100, _clm_5101, _clm_5102, _clm_5103, _clm_5104, _clm_5105, _clm_5106, _clm_5107, _clm_5108, _clm_5109, _clm_5110, _clm_5111, _clm_5112, _clm_5113, _clm_5114, _clm_5115, _clm_5116, _clm_5117, _clm_5118, _clm_5119;
  double *COEFFS = NULL;
  mus_any *IND_NOI = NULL, *AMP_NOI = NULL, *FM_NOI = NULL, *FRB_ENV = NULL, *FRQF = NULL, *PERVIB = NULL, *RANVIB = NULL, *INDF1 = NULL, *FMOSC1 = NULL, *INDF2 = NULL, *FMOSC2 = NULL, *INDF3 = NULL, *FMOSC3 = NULL, *LOC = NULL, *AMPF = NULL, *CARRIER = NULL;
  void *all_gens = NULL;
  mus_long_t clm_beg, clm_end;
  
  all_gens = clm_make_genbag();
  clm_beg = clm_to_mus_long_t(clm_int, 1);
  clm_end = clm_to_mus_long_t(clm_int, 3);
  if (CLM_OSCIL_P(5))
    CARRIER = clm_add_gen_to_genbag(all_gens, 
      mus_make_oscil(
        mus_radians_to_hz(clm_double[CLM_RLOC(5)]),
        clm_double[CLM_RLOC(5) + 1]));
  if (CLM_ENV_P(7))
    AMPF = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(7) + 3), /* breakpoints */
        clm_int[CLM_ILOC(7) + 2], /* num points */
        clm_double[CLM_RLOC(7) + 1], /* scaler */
        clm_double[CLM_RLOC(7) + 2], /* offset */
        clm_double[CLM_RLOC(7)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(7) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_LOCSIG_P(9))
    LOC = clm_add_gen_to_genbag(all_gens, 
      mus_make_locsig(
        clm_double[CLM_RLOC(9)],
        clm_double[CLM_RLOC(9) + 1],
        clm_double[CLM_RLOC(9) + 2],
        clm_int[CLM_ILOC(9) + 2],
        clm_output(), (clm_reverb()) ? mus_channels(clm_reverb()) : 0, clm_reverb(),
        clm_int[CLM_ILOC(9) + 3]));
  if (CLM_OSCIL_P(11))
    FMOSC3 = clm_add_gen_to_genbag(all_gens, 
      mus_make_oscil(
        mus_radians_to_hz(clm_double[CLM_RLOC(11)]),
        clm_double[CLM_RLOC(11) + 1]));
  if (CLM_ENV_P(13))
    INDF3 = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(13) + 3), /* breakpoints */
        clm_int[CLM_ILOC(13) + 2], /* num points */
        clm_double[CLM_RLOC(13) + 1], /* scaler */
        clm_double[CLM_RLOC(13) + 2], /* offset */
        clm_double[CLM_RLOC(13)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(13) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_OSCIL_P(15))
    FMOSC2 = clm_add_gen_to_genbag(all_gens, 
      mus_make_oscil(
        mus_radians_to_hz(clm_double[CLM_RLOC(15)]),
        clm_double[CLM_RLOC(15) + 1]));
  if (CLM_ENV_P(17))
    INDF2 = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(17) + 3), /* breakpoints */
        clm_int[CLM_ILOC(17) + 2], /* num points */
        clm_double[CLM_RLOC(17) + 1], /* scaler */
        clm_double[CLM_RLOC(17) + 2], /* offset */
        clm_double[CLM_RLOC(17)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(17) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_OSCIL_P(19))
    FMOSC1 = clm_add_gen_to_genbag(all_gens, 
      mus_make_oscil(
        mus_radians_to_hz(clm_double[CLM_RLOC(19)]),
        clm_double[CLM_RLOC(19) + 1]));
  if (CLM_ENV_P(21))
    INDF1 = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(21) + 3), /* breakpoints */
        clm_int[CLM_ILOC(21) + 2], /* num points */
        clm_double[CLM_RLOC(21) + 1], /* scaler */
        clm_double[CLM_RLOC(21) + 2], /* offset */
        clm_double[CLM_RLOC(21)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(21) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_RAND_INTERP_P(23))
    RANVIB = clm_add_gen_to_genbag(all_gens, 
      mus_make_rand_interp_with_distribution(
        clm_double[CLM_RLOC(23)],
        clm_double[CLM_RLOC(23) + 1],
        (clm_int[CLM_ILOC(23) + 2] > 0) ? ((double *)(clm_double + CLM_RLOC(23) + 2)) : NULL,
        clm_int[CLM_ILOC(23) + 2]));
  if (CLM_TRIANGLE_WAVE_P(25))
    PERVIB = clm_add_gen_to_genbag(all_gens, 
      mus_make_triangle_wave(
        mus_radians_to_hz(clm_double[CLM_RLOC(25)]),
        clm_double[CLM_RLOC(25) + 2],
        clm_double[CLM_RLOC(25) + 1]));
  if (CLM_ENV_P(27))
    FRQF = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(27) + 3), /* breakpoints */
        clm_int[CLM_ILOC(27) + 2], /* num points */
        clm_double[CLM_RLOC(27) + 1], /* scaler */
        clm_double[CLM_RLOC(27) + 2], /* offset */
        clm_double[CLM_RLOC(27)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(27) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_ENV_P(29))
    FRB_ENV = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(29) + 3), /* breakpoints */
        clm_int[CLM_ILOC(29) + 2], /* num points */
        clm_double[CLM_RLOC(29) + 1], /* scaler */
        clm_double[CLM_RLOC(29) + 2], /* offset */
        clm_double[CLM_RLOC(29)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(29) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_RAND_P(31))
    FM_NOI = clm_add_gen_to_genbag(all_gens, 
      mus_make_rand_with_distribution(
        clm_double[CLM_RLOC(31)],
        clm_double[CLM_RLOC(31) + 1],
        (clm_int[CLM_ILOC(31) + 2] > 0) ? ((double *)(clm_double + CLM_RLOC(31) + 2)) : NULL,
        clm_int[CLM_ILOC(31) + 2]));
  MODULATE = (bool)clm_int[39];
  EASY_CASE = (bool)clm_int[41];
  FROBBER = (bool)clm_int[43];
  if (CLM_VAR_TYPE(45) != CLM_NO_TYPE) COEFFS = (double *)(clm_double + CLM_ARR_RBLOCK(CLM_VAR_ADDR(45)));
  if (CLM_RAND_INTERP_P(33))
    AMP_NOI = clm_add_gen_to_genbag(all_gens, 
      mus_make_rand_interp_with_distribution(
        clm_double[CLM_RLOC(33)],
        clm_double[CLM_RLOC(33) + 1],
        (clm_int[CLM_ILOC(33) + 2] > 0) ? ((double *)(clm_double + CLM_RLOC(33) + 2)) : NULL,
        clm_int[CLM_ILOC(33) + 2]));
  if (CLM_RAND_INTERP_P(35))
    IND_NOI = clm_add_gen_to_genbag(all_gens, 
      mus_make_rand_interp_with_distribution(
        clm_double[CLM_RLOC(35)],
        clm_double[CLM_RLOC(35) + 1],
        (clm_int[CLM_ILOC(35) + 2] > 0) ? ((double *)(clm_double + CLM_RLOC(35) + 2)) : NULL,
        clm_int[CLM_ILOC(35) + 2]));
  VIB = clm_double[17];
  FM3_RAT = clm_double[18];
  FM2_RAT = clm_double[19];
  FM1_RAT = clm_double[20];
  MODULATION = clm_double[21];
  AMP_FUZZ = clm_double[22];
  IND_FUZZ = clm_double[23];
  FUZZ = clm_double[24];
  NOISE_AMOUNT = clm_double[25];
  I = clm_int[47];
  if (clm_beg > clm_end) return(1);
  got_sigint = 0; old_SIGINT = clm_signal(SIGINT, sig_err);                     /* trap SIGINT */
  I = clm_beg;                                                                  /* pass counter */

SAMPLE_LOOP_BEGIN:
  if (got_sigint != 0) {clm_int[0] = (int)got_sigint; goto RUN_ALL_DONE;}
  if (I > clm_end) {I = clm_end; goto RUN_ALL_DONE;}
                                                                                /* (progn */
                                                                                /* (if (/= 0.0 noise-amount) */
  _clm_5060 = (0.0 != NOISE_AMOUNT);                                            /* (neq 0.0 NOISE-AMOUNT) */
  if ((!_clm_5060)) goto L_5058;
                                                                                /* (if (null frobber) */
  _clm_5064 = (!FROBBER);                                                       /* (null FROBBER) */
  if ((!_clm_5064)) goto L_5062;
  _clm_5066 = mus_rand(FM_NOI, 0.0);
  FUZZ = _clm_5066;                                                             /* (setf FUZZ _clm_5066) */
  goto L_5063;
L_5062:
  _clm_5068 = mus_env(FRB_ENV);                                                 /* (env FRB-ENV) */
  FUZZ = _clm_5068;                                                             /* (setf FUZZ _clm_5068) */
L_5063:
  goto L_5059;
L_5058:
L_5059:
  _clm_5071 = mus_env(FRQF);                                                    /* (env FRQF) */
  _clm_5072 = mus_triangle_wave(PERVIB, 0.0);                                   /* (triangle-wave PERVIB) */
  _clm_5073 = mus_rand_interp(RANVIB, 0.0);
                                                                                /* (+ _clm_5071 _clm_5072 _clm_5073) */
  _clm_5070 = ((_clm_5071) + (_clm_5072) + (_clm_5073));
  VIB = _clm_5070;                                                              /* (setf VIB _clm_5070) */
                                                                                /* (if ind-noi */
  if ((!IND_NOI)) goto L_5075;
  _clm_5079 = mus_rand_interp(IND_NOI, 0.0);
                                                                                /* (+ 1.0 _clm_5079) */
  _clm_5078 = ((1.0) + (_clm_5079));
  IND_FUZZ = _clm_5078;                                                         /* (setf IND-FUZZ _clm_5078) */
  goto L_5076;
L_5075:
L_5076:
                                                                                /* (if amp-noi */
  if ((!AMP_NOI)) goto L_5081;
  _clm_5085 = mus_rand_interp(AMP_NOI, 0.0);
                                                                                /* (+ 1.0 _clm_5085) */
  _clm_5084 = ((1.0) + (_clm_5085));
  AMP_FUZZ = _clm_5084;                                                         /* (setf AMP-FUZZ _clm_5084) */
  goto L_5082;
L_5081:
L_5082:
                                                                                /* (if modulate */
  if ((!MODULATE)) goto L_5087;
                                                                                /* (if easy-case */
  if ((!EASY_CASE)) goto L_5090;
  _clm_5094 = mus_env(INDF1);                                                   /* (env INDF1) */
  _clm_5096 = mus_oscil_fm(FMOSC1, VIB);                                        /* (oscil FMOSC1 VIB) */
  _clm_5095 = mus_polynomial(COEFFS, _clm_5096, CLM_ARR_SIZE(CLM_VAR_ADDR(45)));
                                                                                /* (* _clm_5094 _clm_5095) */
  _clm_5093 = ((_clm_5094) * (_clm_5095));
  MODULATION = _clm_5093;                                                       /* (setf MODULATION _clm_5093) */
  goto L_5091;
L_5090:
  _clm_5100 = mus_env(INDF1);                                                   /* (env INDF1) */
                                                                                /* (* fm1-rat vib) */
  _clm_5103 = ((FM1_RAT) * (VIB));
                                                                                /* (+ _clm_5103 fuzz) */
  _clm_5102 = ((_clm_5103) + (FUZZ));
  _clm_5101 = mus_oscil_fm(FMOSC1, _clm_5102);                                  /* (oscil FMOSC1 _clm_5102) */
                                                                                /* (* _clm_5100 _clm_5101) */
  _clm_5099 = ((_clm_5100) * (_clm_5101));
  _clm_5105 = mus_env(INDF2);                                                   /* (env INDF2) */
                                                                                /* (* fm2-rat vib) */
  _clm_5108 = ((FM2_RAT) * (VIB));
                                                                                /* (+ _clm_5108 fuzz) */
  _clm_5107 = ((_clm_5108) + (FUZZ));
  _clm_5106 = mus_oscil_fm(FMOSC2, _clm_5107);                                  /* (oscil FMOSC2 _clm_5107) */
                                                                                /* (* _clm_5105 _clm_5106) */
  _clm_5104 = ((_clm_5105) * (_clm_5106));
  _clm_5110 = mus_env(INDF3);                                                   /* (env INDF3) */
                                                                                /* (* fm3-rat vib) */
  _clm_5113 = ((FM3_RAT) * (VIB));
                                                                                /* (+ _clm_5113 fuzz) */
  _clm_5112 = ((_clm_5113) + (FUZZ));
  _clm_5111 = mus_oscil_fm(FMOSC3, _clm_5112);                                  /* (oscil FMOSC3 _clm_5112) */
                                                                                /* (* _clm_5110 _clm_5111) */
  _clm_5109 = ((_clm_5110) * (_clm_5111));
                                                                                /* (+ _clm_5099 _clm_5104 _clm_5109) */
  _clm_5098 = ((_clm_5099) + (_clm_5104) + (_clm_5109));
  MODULATION = _clm_5098;                                                       /* (setf MODULATION _clm_5098) */
L_5091:
  goto L_5088;
L_5087:
L_5088:
  _clm_5116 = mus_env(AMPF);                                                    /* (env AMPF) */
                                                                                /* (* ind-fuzz modulation) */
  _clm_5119 = ((IND_FUZZ) * (MODULATION));
                                                                                /* (+ vib _clm_5119) */
  _clm_5118 = ((VIB) + (_clm_5119));
  _clm_5117 = mus_oscil_fm(CARRIER, _clm_5118);                                 /* (oscil CARRIER _clm_5118) */
                                                                                /* (* _clm_5116 amp-fuzz _clm_5117) */
  _clm_5115 = ((_clm_5116) * (AMP_FUZZ) * (_clm_5117));
  _clm_5114 = clm_locsig(LOC, I, _clm_5115);
  I++;                                                                          /* increment pass counter and loop */
goto SAMPLE_LOOP_BEGIN;

RUN_ALL_DONE:
  clm_signal(SIGINT,old_SIGINT);
  if (all_gens) clm_free_genbag(all_gens);

  return(1);
}

